name: Build and Upload APK/AAB Artifacts

env:
  main_project_module: app
  playstore_name: IIECat

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set current date
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Clean and build project
        run: ./gradlew clean build

      - name: Build APK Debug
        run: ./gradlew assembleDebug

      - name: Build APK Release
        run: ./gradlew assembleRelease

      - name: Build AAB Release
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }}-${{ env.repository_name }}-debug-APK
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }}-${{ env.repository_name }}-release-APK
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }}-${{ env.repository_name }}-release-AAB
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/
